on:
  pull_request:
    types: [closed]
    branches:
      - master

name: publish
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR merge
        uses: pnpm/action-setup@v4
        if: ${{ github.event.pull_request.merged }}

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        if: ${{ steps.release.outputs.releases_created }}
        with:
          version: 9.x
          run_install: false

      # Setup .npmrc file to publish to npm
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'pnpm'
        if: ${{ steps.release.outputs.releases_created }}

      - name: CI
        run: pnpm install
        if: ${{ steps.release.outputs.releases_created }}

      - name: Build
        run: pnpm build:lib
        if: ${{ steps.release.outputs.releases_created }}

      - name: Publish
        run: pnpm publish
        if: ${{ steps.release.outputs.releases_created }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM }}
